2019-12-18 10:45:50.423 [error] <0.186.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.191.0> exit with reason normal in context child_terminated
2019-12-18 11:00:38.832 [error] <0.201.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.206.0> exit with reason normal in context child_terminated
2019-12-18 11:23:56.655 [error] <0.201.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.206.0> exit with reason normal in context child_terminated
2019-12-18 11:26:11.839 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2019-12-18 11:26:12.181 [error] <0.338.0>@Elixir.ElixirPopularity.RMQPublisher:create_rmq_resources:41 CRASH REPORT Process <0.338.0> with 0 neighbours crashed with reason: no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.ElixirPopularity.RMQPublisher':create_rmq_resources/0 line 41
2019-12-18 11:26:12.186 [error] <0.323.0>@Elixir.ElixirPopularity.RMQPublisher:create_rmq_resources:41 Supervisor 'Elixir.ElixirPopularity.Supervisor' had child 'Elixir.ElixirPopularity.RMQPublisher' started with 'Elixir.ElixirPopularity.RMQPublisher':start_link() at undefined exit with reason no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.ElixirPopularity.RMQPublisher':create_rmq_resources/0 line 41 in context start_error
2019-12-18 11:26:12.187 [error] <0.321.0> CRASH REPORT Process <0.321.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ElixirPopularity.RMQPublisher',{{badmatch,{error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}}},[{'Elixir.ElixirPopularity.RMQPublisher',create_rmq_resources,0,[{file,"lib/rmq_publisher.ex"},{line,41}]},{'Elixir.ElixirPopularity.RMQPublisher',init,0,[{file,"lib/rmq_publisher.ex"},{line,11}]},{'Elixir.GenRMQ.Publisher',init,1,[{file,"lib/publisher.ex"},{line,211}]},{gen_server,...},...]}}},...} in application_master:init/4 line 134
2019-12-18 11:43:33.840 [error] <0.186.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.191.0> exit with reason normal in context child_terminated
2019-12-18 11:43:34.180 [error] <0.329.0>@Elixir.ElixirPopularity.RMQPublisher:create_rmq_resources:41 CRASH REPORT Process <0.329.0> with 0 neighbours crashed with reason: no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.ElixirPopularity.RMQPublisher':create_rmq_resources/0 line 41
2019-12-18 11:43:34.180 [error] <0.314.0>@Elixir.ElixirPopularity.RMQPublisher:create_rmq_resources:41 Supervisor 'Elixir.ElixirPopularity.Supervisor' had child 'Elixir.ElixirPopularity.RMQPublisher' started with 'Elixir.ElixirPopularity.RMQPublisher':start_link() at undefined exit with reason no match of right hand value {error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}} in 'Elixir.ElixirPopularity.RMQPublisher':create_rmq_resources/0 line 41 in context start_error
2019-12-18 11:43:34.181 [error] <0.312.0> CRASH REPORT Process <0.312.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.ElixirPopularity.RMQPublisher',{{badmatch,{error,{auth_failure,"ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile."}}},[{'Elixir.ElixirPopularity.RMQPublisher',create_rmq_resources,0,[{file,"lib/rmq_publisher.ex"},{line,41}]},{'Elixir.ElixirPopularity.RMQPublisher',init,0,[{file,"lib/rmq_publisher.ex"},{line,11}]},{'Elixir.GenRMQ.Publisher',init,1,[{file,"lib/publisher.ex"},{line,211}]},{gen_server,...},...]}}},...} in application_master:init/4 line 134
2019-12-18 11:57:53.295 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2019-12-18 14:28:43.454 [error] <0.1911.0> gen_server <0.1911.0> terminated with reason: {socket_error,timeout}
2019-12-18 14:28:43.519 [error] <0.1911.0> CRASH REPORT Process <0.1911.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 14:28:43.561 [error] <0.1907.0> gen_server <0.1907.0> terminated with reason: {socket_error,timeout}
2019-12-18 14:28:43.562 [error] <0.1907.0> CRASH REPORT Process <0.1907.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 14:28:43.562 [error] <0.1906.0> Supervisor {<0.1906.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11044>, <0.1907.0>, <0.1909.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49398 -> 127.0.0.1:5672">>) at <0.1911.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 14:28:43.563 [error] <0.1906.0> Supervisor {<0.1906.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11044>, <0.1907.0>, <0.1909.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49398 -> 127.0.0.1:5672">>) at <0.1911.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 14:28:43.563 [error] <0.1905.0> Supervisor {<0.1905.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1906.0>, {amqp_params_network,<<"rabbitmq">>,<<"aWFnQ4O0RL+j6BKoZWeTupy+f3YLc7es5pPscM4V9ZGwfc4j2I32hAO3MTX...">>,...}) at <0.1907.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 14:28:43.563 [error] <0.1905.0> Supervisor {<0.1905.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.1906.0>, {amqp_params_network,<<"rabbitmq">>,<<"aWFnQ4O0RL+j6BKoZWeTupy+f3YLc7es5pPscM4V9ZGwfc4j2I32hAO3MTX...">>,...}) at <0.1907.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 14:40:48.309 [error] <0.338.0>@gen_server:call gen_server 'Elixir.ElixirPopularity.RMQPublisher' terminated with reason: no such process or port in call to gen_server:call(<0.2088.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 214
2019-12-18 14:40:48.324 [error] <0.338.0>@gen_server:call CRASH REPORT Process 'Elixir.ElixirPopularity.RMQPublisher' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.2088.0>, {close,200,<<"Goodbye">>}, 60000) in gen_server:call/3 line 214
2019-12-18 14:40:48.326 [error] <0.323.0>@gen_server:call Supervisor 'Elixir.ElixirPopularity.Supervisor' had child 'Elixir.ElixirPopularity.RMQPublisher' started with 'Elixir.ElixirPopularity.RMQPublisher':start_link() at <0.338.0> exit with reason no such process or port in call to gen_server:call(<0.2088.0>, {close,200,<<"Goodbye">>}, 60000) in context child_terminated
2019-12-18 15:42:57.968 [error] <0.2112.0> gen_server <0.2112.0> terminated with reason: {socket_error,timeout}
2019-12-18 15:42:57.974 [error] <0.2112.0> CRASH REPORT Process <0.2112.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 15:42:57.974 [error] <0.2099.0> gen_server <0.2099.0> terminated with reason: {socket_error,timeout}
2019-12-18 15:42:58.006 [error] <0.2099.0> CRASH REPORT Process <0.2099.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 15:42:58.006 [error] <0.2083.0> gen_server <0.2083.0> terminated with reason: {socket_error,timeout}
2019-12-18 15:42:58.009 [error] <0.2083.0> CRASH REPORT Process <0.2083.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 15:42:58.013 [error] <0.2108.0> gen_server <0.2108.0> terminated with reason: {socket_error,timeout}
2019-12-18 15:42:58.014 [error] <0.2108.0> CRASH REPORT Process <0.2108.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 15:42:58.017 [error] <0.2106.0> Supervisor {<0.2106.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2107.0>, {amqp_params_network,<<"rabbitmq">>,<<"9wUoMGevifx2RNzgxtCBDZXL7ar1ijRQ+0vZ8jnb9hjByMJsYCKlQAKRDSl...">>,...}) at <0.2108.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 15:42:58.018 [error] <0.2107.0> Supervisor {<0.2107.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11434>, <0.2108.0>, <0.2110.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49963 -> 127.0.0.1:5672">>) at <0.2112.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 15:42:58.019 [error] <0.2107.0> Supervisor {<0.2107.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11434>, <0.2108.0>, <0.2110.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49963 -> 127.0.0.1:5672">>) at <0.2112.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 15:42:58.020 [error] <0.2094.0> gen_server <0.2094.0> terminated with reason: {socket_error,timeout}
2019-12-18 15:42:58.020 [error] <0.2094.0> CRASH REPORT Process <0.2094.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 15:42:58.021 [error] <0.2093.0> Supervisor {<0.2093.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11319>, <0.2094.0>, <0.2097.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49961 -> 127.0.0.1:5672">>) at <0.2099.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 15:42:58.022 [error] <0.2093.0> Supervisor {<0.2093.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11319>, <0.2094.0>, <0.2097.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49961 -> 127.0.0.1:5672">>) at <0.2099.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 15:42:58.022 [error] <0.2079.0> gen_server <0.2079.0> terminated with reason: {socket_error,timeout}
2019-12-18 15:42:58.023 [error] <0.2079.0> CRASH REPORT Process <0.2079.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 15:42:58.023 [error] <0.2078.0> Supervisor {<0.2078.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11281>, <0.2079.0>, <0.2081.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49944 -> 127.0.0.1:5672">>) at <0.2083.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 15:42:58.024 [error] <0.2078.0> Supervisor {<0.2078.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11281>, <0.2079.0>, <0.2081.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49944 -> 127.0.0.1:5672">>) at <0.2083.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 15:42:58.025 [error] <0.2077.0> Supervisor {<0.2077.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2078.0>, {amqp_params_network,<<"rabbitmq">>,<<"Q0yr2rjMT4AZ88tdZ2y6Ok0nQDa+62xuW0arpvi1sAx7Fo1CFnstw/pJ7Bb...">>,...}) at <0.2079.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 15:42:58.027 [error] <0.2077.0> Supervisor {<0.2077.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2078.0>, {amqp_params_network,<<"rabbitmq">>,<<"Q0yr2rjMT4AZ88tdZ2y6Ok0nQDa+62xuW0arpvi1sAx7Fo1CFnstw/pJ7Bb...">>,...}) at <0.2079.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 15:42:58.028 [error] <0.2106.0> Supervisor {<0.2106.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2107.0>, {amqp_params_network,<<"rabbitmq">>,<<"9wUoMGevifx2RNzgxtCBDZXL7ar1ijRQ+0vZ8jnb9hjByMJsYCKlQAKRDSl...">>,...}) at <0.2108.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 15:42:58.029 [error] <0.2092.0> Supervisor {<0.2092.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2093.0>, {amqp_params_network,<<"rabbitmq">>,<<"qf0xIC1vLLuXYmIOO0nGTTN8Ddjbzwwf/A+bE+51gSnhkQf77Dra72qwul4...">>,...}) at <0.2094.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 15:42:58.030 [error] <0.2092.0> Supervisor {<0.2092.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2093.0>, {amqp_params_network,<<"rabbitmq">>,<<"qf0xIC1vLLuXYmIOO0nGTTN8Ddjbzwwf/A+bE+51gSnhkQf77Dra72qwul4...">>,...}) at <0.2094.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 16:07:55.737 [error] <0.2145.0> gen_server <0.2145.0> terminated with reason: {socket_error,timeout}
2019-12-18 16:07:55.748 [error] <0.2145.0> CRASH REPORT Process <0.2145.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 16:07:55.749 [error] <0.2141.0> gen_server <0.2141.0> terminated with reason: {socket_error,timeout}
2019-12-18 16:07:55.755 [error] <0.2141.0> CRASH REPORT Process <0.2141.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 16:07:55.756 [error] <0.2140.0> Supervisor {<0.2140.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11443>, <0.2141.0>, <0.2143.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50644 -> 127.0.0.1:5672">>) at <0.2145.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 16:07:55.756 [error] <0.2140.0> Supervisor {<0.2140.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.11443>, <0.2141.0>, <0.2143.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50644 -> 127.0.0.1:5672">>) at <0.2145.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 16:07:55.760 [error] <0.2139.0> Supervisor {<0.2139.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2140.0>, {amqp_params_network,<<"rabbitmq">>,<<"VwwA1U8E2n8xVJZvDhT+pNZrP15bFHLPq3FjQtOo1eXh1dLSOn7cF3xuJdK...">>,...}) at <0.2141.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 16:07:55.764 [error] <0.2139.0> Supervisor {<0.2139.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.2140.0>, {amqp_params_network,<<"rabbitmq">>,<<"VwwA1U8E2n8xVJZvDhT+pNZrP15bFHLPq3FjQtOo1eXh1dLSOn7cF3xuJdK...">>,...}) at <0.2141.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 16:36:45.972 [error] <0.201.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.206.0> exit with reason normal in context child_terminated
2019-12-18 17:06:55.106 [error] <0.355.0> gen_server <0.355.0> terminated with reason: {socket_error,timeout}
2019-12-18 17:06:55.140 [error] <0.350.0> gen_server <0.350.0> terminated with reason: {socket_error,timeout}
2019-12-18 17:06:55.182 [error] <0.350.0> CRASH REPORT Process <0.350.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 17:06:55.182 [error] <0.355.0> CRASH REPORT Process <0.355.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 17:06:55.182 [error] <0.370.0> gen_server <0.370.0> terminated with reason: {socket_error,timeout}
2019-12-18 17:06:55.183 [error] <0.348.0> Supervisor {<0.348.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.349.0>, {amqp_params_network,<<"rabbitmq">>,<<"eC3bbrYlhDJzFoGqa5/GuKvDqLInovYpannRCeCOB612F039f3VAQk3sW34...">>,...}) at <0.350.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 17:06:55.183 [error] <0.370.0> CRASH REPORT Process <0.370.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 17:06:55.183 [error] <0.348.0> Supervisor {<0.348.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.349.0>, {amqp_params_network,<<"rabbitmq">>,<<"eC3bbrYlhDJzFoGqa5/GuKvDqLInovYpannRCeCOB612F039f3VAQk3sW34...">>,...}) at <0.350.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 17:06:55.183 [error] <0.349.0> Supervisor {<0.349.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.9822>, <0.350.0>, <0.353.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:51921 -> 127.0.0.1:5672">>) at <0.355.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 17:06:55.184 [error] <0.349.0> Supervisor {<0.349.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.9822>, <0.350.0>, <0.353.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:51921 -> 127.0.0.1:5672">>) at <0.355.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 17:06:55.184 [error] <0.364.0> Supervisor {<0.364.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.10197>, <0.365.0>, <0.368.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:51922 -> 127.0.0.1:5672">>) at <0.370.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 17:06:55.184 [error] <0.365.0> gen_server <0.365.0> terminated with reason: {socket_error,timeout}
2019-12-18 17:06:55.184 [error] <0.364.0> Supervisor {<0.364.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.10197>, <0.365.0>, <0.368.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:51922 -> 127.0.0.1:5672">>) at <0.370.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 17:06:55.185 [error] <0.365.0> CRASH REPORT Process <0.365.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2019-12-18 17:06:55.185 [error] <0.363.0> Supervisor {<0.363.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.364.0>, {amqp_params_network,<<"rabbitmq">>,<<"ldH8QxC4yh31BxwqKhKRnixlMucXKpv+jyYLjM4yh+EBHV8D0bLdtUPNLSh...">>,...}) at <0.365.0> exit with reason {socket_error,timeout} in context child_terminated
2019-12-18 17:06:55.185 [error] <0.363.0> Supervisor {<0.363.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.364.0>, {amqp_params_network,<<"rabbitmq">>,<<"ldH8QxC4yh31BxwqKhKRnixlMucXKpv+jyYLjM4yh+EBHV8D0bLdtUPNLSh...">>,...}) at <0.365.0> exit with reason reached_max_restart_intensity in context shutdown
2019-12-18 17:08:49.816 [error] <0.186.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.191.0> exit with reason normal in context child_terminated
2019-12-18 17:29:45.413 [error] <0.196.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.201.0> exit with reason normal in context child_terminated
2019-12-18 17:32:19.933 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2019-12-18 17:33:34.218 [error] <0.186.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.191.0> exit with reason normal in context child_terminated
2019-12-18 17:58:46.411 [error] <0.206.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.211.0> exit with reason normal in context child_terminated
2019-12-19 15:25:30.013 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
